FROM golang:1.19 AS builder

RUN mkdir /build
WORKDIR /build

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN go build \
        -o ./kafka_exporter \
        kafka_exporter.go

FROM quay.io/prometheus/busybox:latest
WORKDIR /
COPY --from=builder /bin/kafka_exporter .
ENTRYPOINT [ "/bin/kafka_exporter" ]
